### ISSUE TITLE
Remove `await browser.waitForAngularEnabled(false)` from code

### ISSUE THREAD

**Issue by Xotabu4** [delfin123/5-startit-movie-finder-delfin123#1]
All tests has first step as `wait browser.waitForAngularEnabled(false)`
This is not needed for movies-finder.firebaseapp.com since it is angular application

Example:
https://github.com/delfin123/5-startit-movie-finder-delfin123/blob/master/navigation.ts#L6

**Comment by delfin123** [comment]
+
