### ISSUE TITLE
Missed awaits

### ISSUE THREAD

**Issue by Xotabu4** [delfin123/5-startit-movie-finder-delfin123#2]
getText() calls must be with preceding `await`:

- [x] https://github.com/delfin123/5-startit-movie-finder-delfin123/blob/master/navigation.ts#L26
- [x] https://github.com/delfin123/5-startit-movie-finder-delfin123/blob/master/navigation.ts#L18
- [x] https://github.com/delfin123/5-startit-movie-finder-delfin123/blob/master/navigation.ts#L10

**Comment by Xotabu4** [comment]
This will fix unhandled promise rejections errors:

![image](https://user-images.githubusercontent.com/3033972/35858355-cb6aa248-0b44-11e8-8f0a-a86d3c982af9.png)

**Comment by delfin123** [comment]
сделал
